package com.bookexchange.dto;

/**
 * Created by sheke on 2/1/2016.
 */
public enum  NotificationType {
    NEW_USER, RATE_EXCHANGE_RATING, EXCHANGE_CHAIN_REJECTION, EXCHANGE_CHAIN_ACCEPTANCE, EXCHANGE_CHAIN_SUCCESS, DIREXT_EXHANGE_REJECTED, DIRECT_EXCHANGE_ACCEPTED, EXCHANGE_CHAIN_INVITATION
}
